CREATE TABLE IF NOT EXISTS pipeiros (
    id UUID PRIMARY KEY DEFAULT gen_randon_uuid(),
    nome VARCHAR(150) NOT NULL,
    cpf VARCHAR(14) UNIQUE NOT NULL,
    cnh VARCHAR(20) UNIQUE NOT NULL,
    phone VARCHAR(20),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS trucks (
    id UUID PRIMARY KEY DEFAULT gen_randon_uuid(),
    plate VARCHAR(10) UNIQUE NOT NULL,
    capacity_liters INTEGER NOT NULL,
    pipeiro_id UUID NOT NULL REFERENCES pipeiros(id) ON DELETE RESTRICT,
    created_at TIMESTAMP WITH ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cisterns (
    id UUID PRIMARY KEY DEFAULT gen_randon_uuid(),
    nome VARCHAR(50) NOT NULL,
    responsable_name VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    capacity_liters INTEGER NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS deliveries (
    id UUID PRIMARY KEY DEFAULT gen_randon_uuid(),
    cistern_id UUID NOT NULL REFERENCES cisterns(id) ON DELETE RESTRICT,
    truck_id UUID NOT NULL REFERENCES trucks(id) ON DELETE RESTRICT,
    scheduled_date TIMESTAMP WITH ZONE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'AGENDADO',
    volume_delivered INTEGER DEFAULT 0,
    updated_at TIMESTAMP WITH ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH ZONE DEFAULT CURRENT_TIMESTAMP
);
